An 2142 lpactions and transfers from streamline data
FlipsideCrypto/solana-models pull request #113
Opened 2022-10-04 16:14 UTC by tarikceric

Create lp_actions_2 and transfers_2 from streamline tables

2022-10-04 16:53 UTC, desmond-hui requested changes

2022-10-04 16:53 UTC, desmond-hui commented on models/silver/silver__transfers2.sql
> +),
I think you can remove this entire CTE.  `events2` has succeeded flag included in the table

2022-10-04 16:53 UTC, desmond-hui commented on models/silver/silver__transfers2.sql
> +{% endif %}
Missing `else` condition in this block.  See `events2` for example

2022-10-04 16:53 UTC, desmond-hui commented on models/silver/silver__transfers2.sql
> +            LEAST(COALESCE(MAX(block_id), 39824213)+4000000,151386092)
This block of code essentially translates to "The first instance of a transfer starts no earlier than block 39824213".  This is an incorrect statement.

2022-10-04 16:53 UTC, desmond-hui commented on models/silver/silver__transfers2.sql
> +    -- AND block_id between 40000000 and 41000000
Remove code comments

2022-10-04 16:53 UTC, desmond-hui commented on models/silver/silver__transfers2.sql
> +        )
This block of code essentially translates to "The first instance of a transfer starts no earlier than block 39824213". This is an incorrect statement.

2022-10-04 16:53 UTC, desmond-hui commented on models/silver/silver__transfers2.sql
> +    -- AND block_id between 40000000 and 41000000
remove code comments

2022-10-04 16:53 UTC, desmond-hui commented on models/silver/silver__staking_lp_actions2.sql
> +{{ config(
See change requests from `transfers2` as many of the same comments apply here

2022-10-04 19:19 UTC, tarikceric commented on models/silver/silver__transfers2.sql
> +),
CTE has been removed and replaced with "AND succeeded = TRUE" in first CTE selecting from events2

2022-10-04 19:19 UTC, tarikceric commented on models/silver/silver__transfers2.sql
> +{% endif %}
condition added, from block_id 475146

2022-10-04 19:19 UTC, tarikceric commented on models/silver/silver__transfers2.sql
> +            LEAST(COALESCE(MAX(block_id), 39824213)+4000000,151386092)
Now using block_id 475146

2022-10-04 20:23 UTC, desmond-hui requested changes

2022-10-04 20:23 UTC, desmond-hui commented on models/silver/silver__transfers2.sql
> +        TABLE(FLATTEN(i.value :instructions)) ii
Use the inner_instructions from events2 instead so that we can take advantage of the `succeeded` column within events2

2022-10-05 04:03 UTC, tarikceric commented on models/silver/silver__transfers2.sql
> +        TABLE(FLATTEN(i.value :instructions)) ii
Revised to select from events2 and leverage filtering by `succeeded` column

2022-10-05 22:50 UTC, desmond-hui approved these changes

2022-10-05 22:55 UTC, merged