An 2143 nft models from streamline data
FlipsideCrypto/solana-models pull request #124
Opened 2022-10-07 21:24 UTC by tarikceric

2022-10-07 21:32 UTC, desmond-hui requested changes

2022-10-07 21:34 UTC, desmond-hui commented on models/silver/silver__mint_actions2.sql
> +    WHERE block_timestamp :: date >= '2020-10-07'
Where did this `block_timesamp` come from?

2022-10-07 21:36 UTC, desmond-hui commented on models/silver/nfts/silver__nft_mint_price_generic2.sql
> +AND block_timestamp :: date >= '2021-06-02'
This needs to be a range

2022-10-07 22:20 UTC, desmond-hui commented on models/silver/nfts/silver__nft_mint_price_generic2.sql
> +        )
This should be block_timestamp

2022-10-08 00:24 UTC, desmond-hui requested changes

2022-10-08 00:24 UTC, desmond-hui commented on models/silver/nfts/silver__nft_sales_magic_eden_v1_2.sql
> +  t.block_timestamp :: date >= '2021-09-07'
These should be a range

2022-10-08 00:24 UTC, desmond-hui commented on models/silver/nfts/silver__nft_sales_magic_eden_v2_2.sql
> +        t.block_timestamp :: DATE >= '2022-01-08'
these should be a range

2022-10-08 00:24 UTC, desmond-hui commented on models/silver/nfts/silver__nft_sales_magic_eden_v2_2.sql
> +    AND e.block_timestamp :: DATE >= '2022-01-08' -- no ME V2 contract before this date
this should be a range

2022-10-08 00:24 UTC, desmond-hui commented on models/silver/nfts/silver__nft_sales_magic_eden_v2_2.sql
> +    AND e.block_timestamp:: DATE >= '2022-01-08' -- no ME V2 contract before this date
this should be a range

2022-10-08 00:24 UTC, desmond-hui commented on models/silver/nfts/silver__nft_sales_magic_eden_v2_2.sql
> +    WHERE block_timestamp :: DATE >= '2022-01-08' -- no ME V2 contract before this date
this should be a range

2022-10-08 00:25 UTC, desmond-hui commented on models/silver/nfts/silver__nft_sales_magic_eden_v2_2.sql
> +            instruction :accounts [1] :: STRING END AS seller
this logic was recently changed, make sure it matches the current table

2022-10-08 00:27 UTC, desmond-hui requested changes

2022-10-08 00:27 UTC, desmond-hui commented on models/silver/nfts/silver__nft_sales_magic_eden_v2_2.sql
> +            OR inner_instruction_type = 'create'
This was also changed in the recent update.  See this commit https://github.com/FlipsideCrypto/solana-models/commit/cf75e9f70f6fb5581536076e753579756d2c890a

2022-10-08 01:08 UTC, tarikceric commented on models/silver/nfts/silver__nft_sales_magic_eden_v2_2.sql
> +    WHERE block_timestamp :: DATE >= '2022-01-08' -- no ME V2 contract before this date
added range

2022-10-08 01:08 UTC, tarikceric commented on models/silver/nfts/silver__nft_sales_magic_eden_v2_2.sql
> +    AND e.block_timestamp:: DATE >= '2022-01-08' -- no ME V2 contract before this date
added range

2022-10-08 01:09 UTC, tarikceric commented on models/silver/nfts/silver__nft_sales_magic_eden_v1_2.sql
> +  t.block_timestamp :: date >= '2021-09-07'
added range

2022-10-08 01:09 UTC, tarikceric commented on models/silver/nfts/silver__nft_sales_magic_eden_v2_2.sql
> +    AND e.block_timestamp :: DATE >= '2022-01-08' -- no ME V2 contract before this date
added range

2022-10-08 01:09 UTC, tarikceric commented on models/silver/nfts/silver__nft_sales_magic_eden_v2_2.sql
> +        t.block_timestamp :: DATE >= '2022-01-08'
added range

2022-10-08 01:15 UTC, desmond-hui approved these changes

2022-10-08 01:19 UTC, merged