Hadeswap NFT sales
FlipsideCrypto/solana-models pull request #129
Opened 2022-10-12 21:16 UTC by jkallogjeri

2022-10-13 12:20 UTC, jhuhnke requested changes

2022-10-13 12:20 UTC, jhuhnke commented on models/silver/nfts/silver__nft_sales_hadeswap.sql
> +WHERE program_id = 'hadeK9DLv9eA7ya5KCTqSvSvRZeJC3JgD5a9Y3CNbvu'
Can we add a where clause in that limits the block_timestamp range to on and after 2022-09-22? This is the program launch date

2022-10-13 12:20 UTC, jhuhnke commented on models/silver/nfts/silver__nft_sales_hadeswap.sql
> +    AND _inserted_timestamp >= (SELECT MAX(_inserted_timestamp) FROM {{ this }})
We are hotswapping in the historical backfill in our Solana models today, and since the data is so large it will take super long to run a FR on a majority of models. Can we get incremental logic similar to this added in? 

`{% if is_incremental() and env_var(
    'DBT_IS_BATCH_LOAD',
    "false"
) == "true" %}
WHERE
    block_timestamp :: DATE BETWEEN (
        SELECT
            LEAST(DATEADD(
                'day',
                1,
                COALESCE(MAX(block_timestamp) :: DATE, '2022-01-08')),'2022-10-05')
                FROM
                    {{ this }}
        )
        AND (
        SELECT
            LEAST(DATEADD(
            'day',
            30,
            COALESCE(MAX(block_timestamp) :: DATE, '2022-01-08')),'2022-10-05')
            FROM
                {{ this }}
        )
{% elif is_incremental() %}
WHERE
    _inserted_timestamp >= (
        SELECT
            MAX(_inserted_timestamp)
        FROM
            {{ this }}
    )
{% else %}
WHERE
    block_timestamp :: DATE BETWEEN '2022-01-08' -- no ME V2 contract before this date
    AND '2022-02-08'
{% endif %}`

2022-10-13 21:30 UTC, jkallogjeri commented on models/silver/nfts/silver__nft_sales_hadeswap.sql
> +    AND _inserted_timestamp >= (SELECT MAX(_inserted_timestamp) FROM {{ this }})
For some reason it throws error when I added the new blob. I sent error + code to you on slack. Check when you have a sec

2022-10-16 20:04 UTC, jhuhnke approved these changes

2022-10-16 20:04 UTC, merged