get token metadata macro
FlipsideCrypto/solana-models pull request #150
Opened 2022-11-04 15:26 UTC by desmond-hui

- Adding a macro to run udf api call for getting raw token metadata that is not available from CoinMarketCap or CoinGecko

2022-11-04 17:59 UTC, drethereum requested changes

2022-11-04 17:59 UTC, drethereum commented on data/seed__missing_token_metadata.csv
> +
remove null row

2022-11-04 18:00 UTC, drethereum approved these changes

2022-11-04 18:19 UTC, merged

2022-11-05 06:55 UTC, jhuhnke approved these changes