An 2455/intermediate swaps raydium
FlipsideCrypto/solana-models pull request #161
Opened 2022-11-22 19:49 UTC by tarikceric

Create a separate model for intermediate swaps performed on Raydium

2022-11-23 01:24 UTC, desmond-hui requested changes

2022-11-23 01:31 UTC, desmond-hui requested changes

2022-11-23 01:31 UTC, desmond-hui commented on models/silver/swaps/silver__swaps_intermediate_raydium.sql
> +            '5quBtoiQqxF9Jv6KYKctB59NT3gtJD2Y65kdnB1Uev3h',
It's probably worth adding these other two 

```
export const LIQUIDITY_POOL_PROGRAM_ID_V2 = 'RVKd61ztZW9GUwhRbbLoYVRE5Xf1B2tVscKqwZqXgEr'
export const LIQUIDITY_POOL_PROGRAM_ID_V3 = '27haf8L6oxUeXrHrgEgsexjSY5hbVUWEmvv9Nyxg8vQv'
```

resource https://github.com/raydium-io/raydium-ui/blob/f1e0d0ab5b1f7ccb90e84e5a81cd58d54b69ac3c/src/utils/ids.ts

2022-11-23 01:31 UTC, desmond-hui commented on models/silver/swaps/silver__swaps_intermediate_raydium.sql
> +            '93BgeoLHo5AdNbpqy9bD12dtfxtA5M2fh3rj72bE35Y3',
Possibly remove `93BgeoLHo5AdNbpqy9bD12dtfxtA5M2fh3rj72bE35Y3`? Might not be a direct swap...needs further investigation

2022-11-28 17:35 UTC, tarikceric commented on models/silver/swaps/silver__swaps_intermediate_raydium.sql
> +WITH base_events AS(
New filters added

2022-11-28 17:36 UTC, tarikceric commented on models/silver/swaps/silver__swaps_intermediate_raydium.sql
> +            '5quBtoiQqxF9Jv6KYKctB59NT3gtJD2Y65kdnB1Uev3h',
Txs with these program_ids are all LP actions and not swaps, so they were not added

2022-11-30 01:33 UTC, desmond-hui approved these changes

2022-11-30 01:34 UTC, merged