prices fix
FlipsideCrypto/solana-models pull request #166
Opened 2022-11-30 21:52 UTC by jhuhnke

2022-11-30 22:15 UTC, desmond-hui requested changes

2022-11-30 22:15 UTC, desmond-hui commented on models/silver/prices/silver__token_prices_coin_market_cap_hourly.sql
> -            11212
Looks like star-atlas got removed?  Not sure what else is was deleted that wasn't meant to be

2022-12-01 06:24 UTC, jhuhnke commented on models/silver/prices/silver__token_prices_coin_market_cap_hourly.sql
> -            11212
Ok, added the 5 escapee shitcoins back in

2022-12-01 15:29 UTC, desmond-hui approved these changes

2022-12-01 19:31 UTC, merged