AN-2517 cross chain and solscan address to symbol to price
FlipsideCrypto/solana-models pull request #176
Opened 2022-12-06 19:21 UTC by eric-laurello

1. UDFs for solscan
2. Token Metadata
3. EZ Prices

2022-12-06 20:02 UTC, desmond-hui requested changes

2022-12-06 20:02 UTC, desmond-hui commented on models/core/core__ez_token_prices.sql
> +WHERE
Output doesnt look to be showing CMC prices properly.  Example

`select *
from solana_dev.core.ez_token_prices
where token_address = '4k3Dyjzvzp8eMZWUXbBCjEvwSkkk59S5iCNLY3QrkX6R'
order by recorded_hour desc;`

This is Raydium token and is in the silver prices and the token metadata mapping is there

`select *
from solana_dev.silver.token_prices_coin_market_cap_hourly
where id = 8526
order by recorded_hour desc;`

`select *
from solana_dev.silver.token_metadata
where token_address = '4k3Dyjzvzp8eMZWUXbBCjEvwSkkk59S5iCNLY3QrkX6R';`

2022-12-06 22:48 UTC, desmond-hui requested changes

2022-12-06 22:48 UTC, desmond-hui commented on models/bronze_api/bronze_api__solscan_token.sql
> +    base
Shouldn't this be left as raw data and then we transform it in the silver layer?  That would follow the pattern w/ the other macro + our current calls to streamline

2022-12-06 22:48 UTC, desmond-hui commented on models/bronze_api/bronze_api__solscan_token.sql
> +    DATA :data :"address" :: STRING AS token_address,
These two will always be the same value

2022-12-06 22:48 UTC, desmond-hui commented on models/silver/swaps/silver__swaps.sql
> +{{ config(
Please change name of this model.  We are using this in current development as part of the swap models refactoring

2022-12-06 22:48 UTC, desmond-hui commented on models/bronze_api/bronze_api__solscan_token.sql
> +{{ config(
This took > 300s to run to get metadata for 1 token? That seems too long, all the incrementals combined only take 15-20mins on a medium.  I am reluctant to add 300s of overhead for 1 token

2022-12-06 22:54 UTC, desmond-hui requested changes

2022-12-06 22:54 UTC, desmond-hui commented on models/core/core__dim_tokens.sql
> +{{ config(
One of these token addresses is a URL for some reason

`select *
from solana_dev.core.dim_tokens
where symbol = 'COFFEE';`

2022-12-07 00:02 UTC, eric-laurello commented on models/bronze_api/bronze_api__solscan_token.sql
> +    DATA :data :"address" :: STRING AS token_address,
some of the calls do not return a value for address so I wanted to keep both for the sake of knowing that.

2022-12-07 00:02 UTC, eric-laurello commented on models/silver/swaps/silver__swaps.sql
> +{{ config(
will that new version include the same data? should I merge that change into my branch?

2022-12-07 17:46 UTC, desmond-hui commented on models/silver/swaps/silver__swaps.sql
> +{{ config(
Same columns but different data.  Probably not too relevant though because I dont see a significant change in terms of the mints that matter

2022-12-08 17:45 UTC, desmond-hui approved these changes

2022-12-08 19:00 UTC, merged