An 2248/lp actions
FlipsideCrypto/solana-models pull request #191
Opened 2022-12-19 17:29 UTC by tarikceric

Models for Liquidity Pool actions performed on dexes (Saber, Raydium, Orca). Each record has a 'Liquidity Provider' which is the account interacting with the Liquidity Pool. The outputs consist of separate rows for each `deposit`/`withdraw` of a base token, as well as `burn_lp`/`mint lp` for LP token actions.

Key differences between models:
- Saber: The `DecZY86MU5Gj7kppfUCEmd4LbXXuyZH1yHaP2NTqdiZB` program id is used to get the true unwrapped token
- Orca: Actions using `whirlpool` utilize NFTs to represent LP ownership, so LP token amounts will always be 1 with null `mint`

2022-12-19 19:30 UTC, desmond-hui requested changes

2022-12-19 19:30 UTC, desmond-hui commented on models/silver/liquidity_pool/silver__liquidity_pool_actions_raydium.sql
> +SELECT
Can we add those `withdrawpnl` events?

2022-12-19 19:30 UTC, desmond-hui commented on models/silver/liquidity_pool/silver__liquidity_pool_actions_saber.sql
> +SELECT
Possibly missing actions?  Withdraws for USDC/USDCet pool much greater than deposits

`select 'deposit', sum(amount)
from solana_dev.silver.liquidity_pool_actions_saber
where liquidity_pool_address = 'GokA1R67GqSavkd15zR62QD68Tuc5AEfvjssntVDEbM8'
and mint = 'EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v'
and action = 'deposit'
union 
select 'withdraw', sum(amount)
from solana_dev.silver.liquidity_pool_actions_saber
where succeeded
and liquidity_pool_address = 'GokA1R67GqSavkd15zR62QD68Tuc5AEfvjssntVDEbM8'
and mint = 'EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v'
and action = 'withdraw'
;`

2022-12-20 17:00 UTC, tarikceric commented on models/silver/liquidity_pool/silver__liquidity_pool_actions_orca.sql
> +            AND program_id = 'whirLbMiicVdio4qvUfM5KAg6Ct8VwpYzGff3uctyCc' THEN 'lp_action'
It's used to initially label whirlpool `deposits`/`withdraws`, since there are no noticeable differences that can be used to differentiate between the two. I then identify the `lp_action `as its standard action further down the model in the `temp_final `cte.

2022-12-20 17:05 UTC, tarikceric commented on models/silver/liquidity_pool/silver__liquidity_pool_actions_orca.sql
> +SELECT
This was an issue with some mapping where it was incorrectly leaving those records with `null` actions, so I added back in the `multisig_account_mapping` cte

2022-12-20 17:08 UTC, tarikceric commented on models/silver/liquidity_pool/silver__liquidity_pool_actions_orca.yml
> +        description: "{{ doc('stake_pool_action') }}"
You're correct that there should not be, and has been fixed with additional mapping

2022-12-20 17:09 UTC, tarikceric commented on models/silver/liquidity_pool/silver__liquidity_pool_actions_raydium.sql
> +SELECT
`withdrawpnl` events have been added as its own `action`

2022-12-20 17:20 UTC, tarikceric commented on models/silver/liquidity_pool/silver__liquidity_pool_actions_saber.sql
> +SELECT
Great catch! This has been fixed where older tx's are included.

2023-02-20 16:09 UTC, closed without merging