An 867 magic eden
FlipsideCrypto/solana-models pull request #20
Opened 2022-03-10 19:58 UTC by jhuhnke

2022-03-11 00:42 UTC, desmond-hui requested changes

2022-03-11 00:42 UTC, desmond-hui commented on models/silver/silver__nfts_magic_eden_v1.sql
> +      (price_0 + price_1 + price_2 + price_3 + price_4 + price_5) AS sale_amount,
The current methodology will not scale, it is capped at 5 amounts.  If there are 6 or more amounts, the sales price is not correct.  Example `2QY63qHsgW9A9NmBQpceCAe4kLSMPTjyroo5J6X2pkZ7zws2UmzRnoYSC1DmCbRgHRdM3gzh7wmXp1p5ddP4R12X`

This should be done by flattening the `inner_instruction:instructions` so that you get an a row per `inner_instruction`.  Use that to pull out the solana amount within each `inner_instruction` and then group the records back together and sum the amounts.

2022-03-11 00:42 UTC, desmond-hui commented on models/silver/silver__nfts_magic_eden_v2.sql
> +ON e.tx_id = p.tx_id AND e.index = p.index
Same comments as for V1 instruction.  I think you can find the mint from the inner_instructions for a v2 sale

2022-03-11 00:42 UTC, desmond-hui commented on models/silver/silver__nfts_magic_eden_v2.sql
> +WHERE t.ct = 3
I think there are NFT sales w/ < 3 events.

https://solscan.io/tx/4P2rPf6swFa27aBqaRxLso99ctB72rxVPGoA5yt7PREUzDf1CGpnAkMr5t2Lfd6DG3jJoDNT3L8zy2CrcjyVpFJS

^ this one looks like a sale to me, but it doesnt have the instruction that gives the sale total

2022-03-11 00:42 UTC, desmond-hui commented on models/silver/silver__nfts_magic_eden_v2.sql
> +    GROUP BY tx_id
If you need to do a count filter, you can do it here with a `having` clause.

`GROUP BY tx_id
HAVING count(tx_id) = 3`

2022-03-11 15:58 UTC, jhuhnke commented on models/silver/silver__nfts_magic_eden_v1.sql
> +ON t.tx_id = p.tx_id AND t.index = p.index
Not even sure this is necessary. There is a mint field in the inner instructions - we can just pull that.

2022-03-11 19:29 UTC, desmond-hui requested changes

2022-03-11 19:29 UTC, desmond-hui commented on models/silver/silver__nfts_magic_eden_v2.sql
> +),
This CTE isnt necessary.  You can get the max event index for the transaction in the above CTE since you are already grouping by transaction and select from the events table

`max(index) as last_index`

2022-03-11 19:29 UTC, desmond-hui commented on models/silver/silver__nfts_magic_eden_v2.sql
> +),
I think this can be reduced to a single CTE where we filter to the inner_instructions we want per transaction.  Again you can use `max()` to figure out the max inner instruction index per transaction so that you can use it to ignore that record down the line.  See example below, you don't need a group by if you use `over (partition by ...)`

`max(i.index) over (partition by e.tx_id, e.index, NFT) as max_inner_index`

2022-03-11 19:31 UTC, desmond-hui commented on models/silver/silver__nfts_magic_eden_v1.sql
> +ON p.tx_id = t.tx_id AND p.account = t.account
table reference needs to be parameterized

2022-03-11 19:37 UTC, jhuhnke commented on models/silver/silver__nfts_magic_eden_v1.sql
> +    FROM "SOLANA_DEV"."SILVER"."EVENTS",
I missed this... whoops

2022-03-11 19:56 UTC, jhuhnke commented on models/silver/silver__nfts_magic_eden_v1.yml
> +            - NFT
This needs to be the unique key due to bundled sales of NFTs. https://solscan.io/tx/31jptwqYr8EPqKBhrS4Ah1eyZhqV3mTh8YAMbAtXo5SgVNpYRCs6foEGkT475aeP2tbfytpLenJsUU66AyvHo2Ed

Going to represent the price differently

2022-03-11 21:49 UTC, jhuhnke commented on models/silver/silver__nfts_magic_eden_v2.sql
> +),
Found an easier way to pull the price rather than sum everything - killed off all these CTEs and used the easier way

2022-03-17 03:27 UTC, nickpayiatis approved these changes

2022-03-17 03:30 UTC, merged