An 3931/token nft burn mint actions
FlipsideCrypto/solana-models pull request #360
Opened 2023-10-06 13:53 UTC by tarikceric

- `silver__dim_mint_types.sql` identifies the mint_type and mint_standard_type for each mint
- create `nft_burn_actions`, `token_burn_actions` and `token_mint_actions` silver and gold tables. `token_mint_actions` only contains mint events and not mint initializations
- A `nft_mint_actions` table was not included because the existing `nft_mints` is a more enhanced version

2023-10-06 15:38 UTC, desmond-hui requested changes

2023-10-06 15:38 UTC, desmond-hui commented on models/silver/labels/silver__dim_mint_types.sql
> +        TABLE(FLATTEN(inner_instruction :instructions)) i
I think you can use this `ARRAY_CONTAINS('metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s'::variant,e.inner_instruction_program_ids)` before you flatten every event's inner_instruction

2023-10-06 15:38 UTC, desmond-hui commented on models/silver/tokens/silver__token_burn_actions.sql
> +    INNER JOIN solana_dev.silver.dim_mint_types b
missing `ref()`

2023-10-06 15:38 UTC, desmond-hui commented on models/silver/tokens/silver__token_mint_actions.sql
> +    INNER JOIN solana_dev.silver.dim_mint_types b
missing `ref()`

2023-10-06 15:38 UTC, desmond-hui commented on models/silver/nfts/silver__nft_burn_actions.sql
> +    INNER JOIN solana_dev.silver.dim_mint_types b
missing `ref()`

2023-10-06 15:38 UTC, desmond-hui commented on models/gold/core/core__fact_nft_burn_actions.sql
Do we need `nft_mint_actions`?

2023-10-06 15:38 UTC, desmond-hui commented on models/silver/labels/silver__dim_mint_types.sql
> +        {{ ref('silver__events') }} e
Should we not be predicating this by having `initialization` as the subset and joining to events instead of querying all of events? From looking at the downstream CTEs, only the metaplex events where the tx_id = the initilization cte tx_id is used.

2023-10-06 15:38 UTC, desmond-hui commented on models/silver/labels/silver__dim_mint_types.sql
> +        TABLE(FLATTEN(inner_instruction :instructions)) i
I ran the query up to the `metaplex_events` part with some optimizations vs. current state on a M to test whether the changes had a perf impact...here are preliminary results

Current State: Canceled after 14min+
Suggested Changes: Completed in ~10mins

2023-10-10 03:53 UTC, tarikceric commented on models/gold/core/core__fact_nft_burn_actions.sql
Added silver and core `nft_mint_actions` - the existing `nft_mints` seems like a more enhanced version but it may be useful

2023-10-10 03:56 UTC, tarikceric commented on models/silver/labels/silver__dim_mint_types.sql
> +        {{ ref('silver__events') }} e
updated to use `initialization` as the base table and `metaplex_events` is joined to it. Also discovered that some mints may not have an initialize event (mainly edition NFTs), so the `initialization` was adjusted to include all events from `mint_actions`.

2023-10-10 03:57 UTC, tarikceric commented on models/silver/labels/silver__dim_mint_types.sql
> +        AND block_timestamp :: DATE > '2022-06-01'
good catch, it should be `2021-06-01` which is the first instance of the metaplex program

2023-10-10 03:57 UTC, tarikceric commented on models/silver/labels/silver__dim_mint_types.sql
> +metaplex_events AS (
incremental logic added

2023-10-11 17:03 UTC, tarikceric commented on models/silver/labels/silver__dim_mint_types.sql
> +        TABLE(FLATTEN(inner_instruction :instructions)) i
added in filter which improved performance - full refresh w 2xl went from 22min to 15min

2023-10-12 18:06 UTC, desmond-hui requested changes

2023-10-12 18:06 UTC, desmond-hui commented on models/silver/labels/silver__mint_types.sql
> +        metaplex_events
I am under the assumption that this model does not care about `NULL metaplex_event_types` therefore I think we should filter them out at this step

`WHERE 
        metaplex_event_type IS NOT NULL`

2023-10-12 18:06 UTC, desmond-hui commented on models/silver/nfts/silver__nft_mint_actions.sql
This model did not execute successfully on incremental load

2023-10-12 18:46 UTC, desmond-hui commented on models/gold/nft/core__fact_nft_burn_actions.sql
> +    MIN_STANDARD_TYPE
typo

2023-10-12 19:52 UTC, tarikceric commented on models/silver/labels/silver__mint_types.sql
> +        metaplex_events
added

2023-10-12 19:52 UTC, tarikceric commented on models/silver/nfts/silver__nft_mint_actions.sql
fixed incremental

2023-10-12 19:53 UTC, tarikceric commented on models/gold/nft/core__fact_nft_burn_actions.sql
> +    MIN_STANDARD_TYPE
fixed

2023-10-12 19:53 UTC, tarikceric commented on models/silver/labels/silver__mint_types.sql
> +        )
updated

2023-10-13 14:18 UTC, desmond-hui approved these changes

2023-10-16 19:04 UTC, merged