An 4136/nft collection names
FlipsideCrypto/solana-models pull request #409
Opened 2023-11-17 17:22 UTC by tarikceric

- Replace old approach to NFT metadata + announce column deprecation on gold NFT table
- grab collection names from Solscan by getting info for one NFT per `group_value` (aka the collection id from Helius) and then join to all other mints with the same `group_value`

2023-11-17 18:00 UTC, desmond-hui requested changes

2023-11-17 18:00 UTC, desmond-hui commented on models/gold/nft/nft__dim_nft_metadata.sql
Is this going to be exposed the moment we merge this or would we want to wait for backfill to complete?

2023-11-17 18:08 UTC, desmond-hui requested changes
I think `models/bronze/bronze_api/bronze_api__helius_nft_metadata.sql` needs to be clustered by `_inserted_timestamp::date`

2023-11-17 18:22 UTC, desmond-hui requested changes

2023-11-17 18:22 UTC, desmond-hui commented on models/silver/metadata/silver__nft_collection.sql
> +            distinct collection_id
`collection_id` is already distinct since it is the primary key

2023-11-17 18:22 UTC, desmond-hui commented on models/silver/metadata/silver__nft_collection.sql
> +response AS ({% for item in range(1, 150) %}
What is the reason to loop instead of calling 150 in 1 query? Also why was 150 chosen?

2023-11-17 18:22 UTC, desmond-hui commented on models/silver/metadata/silver__nft_collection.sql
> +        mint,
I don't think you need this...The helius `collection_id` is a valid mint within solana that represents the collection...I think if you pass that in you will get the appropriate collection infomation from solscan

2023-11-17 21:30 UTC, tarikceric commented on models/silver/metadata/helius/silver__helius_nft_metadata.sql
> +    -- items.value ['compression'] AS compression,
removed

2023-11-17 21:30 UTC, tarikceric commented on models/silver/metadata/helius/silver__helius_nft_metadata.sql
> +    -- items.value ['royalty'] AS royalty,
removed

2023-11-17 21:31 UTC, tarikceric commented on models/silver/metadata/helius/silver__helius_nft_metadata.sql
> +    {{ dbt_utils.generate_surrogate_key(['mint']) }} AS nft_metadata_id,
updated

2023-11-17 22:09 UTC, tarikceric commented on models/silver/metadata/silver__nft_collection.sql
> +response AS ({% for item in range(1, 150) %}
there were about 100 +/- avg new distinct collections occuring daily. I was only able to pass in 2 addresses at once before it returned an error, and the docs don't really state if it accepts numerous addresses at once

2023-11-17 22:10 UTC, tarikceric commented on models/silver/metadata/silver__nft_collection.sql
> +        mint,
n/a per slack convo

2023-11-17 22:15 UTC, tarikceric commented on models/silver/metadata/silver__nft_collection.sql
> +            distinct collection_id
removed distinct

2023-11-17 22:26 UTC, tarikceric commented on models/silver/metadata/silver__nft_collection.sql
> +    END AS nft_collection_name,
outputting solscan_collection_id, and n/a for helius_nft_metadata_id per slack convo

2023-11-20 19:23 UTC, tarikceric commented on models/silver/metadata/silver__nft_collection.sql
> +        livequery_dev.live.udf_api('GET', 'https://pro-api.solscan.io/v1.0/nft/token/info/' || (mint), OBJECT_CONSTRUCT('Accept', 'application/json', 'token', (
updated

2023-11-20 21:48 UTC, desmond-hui commented on models/silver/metadata/silver__nft_collection.sql
> +response AS ({% for item in range(1, 150) %}
Can you elaborate on this? "I was only able to pass in 2 addresses at once before it returned an error". How are you passing in 2 addresses at a time? I am not seeing this behavior when I am testing.

2023-11-20 21:56 UTC, desmond-hui requested changes

2023-11-20 23:16 UTC, tarikceric commented on models/silver/metadata/silver__nft_collection.sql
> +response AS ({% for item in range(1, 150) %}
updated to remove loop and instead run query once with 150 rows

2023-11-20 23:16 UTC, tarikceric commented on models/gold/nft/nft__dim_nft_metadata.yml
> +        description: "{{ doc('id') }}"
added pk

2023-11-20 23:16 UTC, tarikceric commented on models/silver/metadata/silver__nft_collection.yml
> +  - name: silver__nft_collection
Updated, although I'm curious, wouldn't that be the same as the existing `unique` test on `COLLECTION_ID'?

2023-11-21 16:01 UTC, desmond-hui commented on models/silver/metadata/silver__nft_collection.yml
> +  - name: silver__nft_collection
You are right, I missed the `-unique` test when I made that comment. I updated to remove the combo columns test

2023-11-22 17:46 UTC, desmond-hui requested changes

2023-11-27 14:50 UTC, tarikceric commented on models/silver/metadata/silver__nft_collection.sql
> +limit 150
updated

2023-11-27 15:29 UTC, desmond-hui approved these changes

2023-11-30 00:55 UTC, merged