An 4097/dim idl
FlipsideCrypto/solana-models pull request #451
Opened 2024-01-17 16:47 UTC by tarikceric

Add DIM table containing information on IDLs/programs that are being decoded.

2024-01-17 18:02 UTC, desmond-hui requested changes

2024-01-17 21:54 UTC, tarikceric commented on models/silver/idls/silver__idl.sql
> +        ON A.program_id = b.program_id
removed

2024-01-17 21:55 UTC, tarikceric commented on models/silver/idls/silver__idl.sql
> +    tags = ['scheduled_non_core']
added

2024-01-17 23:23 UTC, tarikceric commented on models/silver/idls/silver__idl.sql
> +WITH idls AS (
add incremental logic to only check decoded_instructions from last two hours, and updates only if the min(block_id) from the first cte is less than the existing earliest_decoded_block

2024-01-18 16:13 UTC, desmond-hui approved these changes
See comment

2024-01-18 17:13 UTC, merged