ez_decoded---updates
FlipsideCrypto/solana-models pull request #469
Opened 2024-01-26 19:12 UTC by eric-laurello

2024-01-27 14:39 UTC, desmond-hui requested changes

2024-01-27 14:39 UTC, desmond-hui commented on models/silver/parser/silver__decoded_instructions.sql
> +    cluster_by = ['program_id','block_timestamp::DATE','_inserted_timestamp::DATE'],
I have some reservations about putting program_id first in terms of incremental loading performance. Can we make this a V2 table for a week and create a separate GHA workflow to run this in parallel to see performance before we make the change?

2024-01-27 14:39 UTC, desmond-hui commented on models/gold/core/core__ez_events_decoded.sql
>      A.decoded_instruction,
I think we should split this to be

```
A.decoded_instruction:accounts::array as decoded_accounts,
A.decoded_instruction:args::variant as decoded_args,
A.decoded_instruction:error::string as decoding_error
```

2024-01-29 14:22 UTC, eric-laurello commented on models/gold/core/core__ez_events_decoded.sql
>      A.decoded_instruction,
@desmond-hui  Were you thinking about landing these so we can SO them or just breaking them out in the view is enough?

2024-01-29 14:47 UTC, desmond-hui commented on models/gold/core/core__ez_events_decoded.sql
>      A.decoded_instruction,
No SO, i think view is enough

2024-02-01 15:45 UTC, desmond-hui approved these changes

2024-02-02 01:48 UTC, merged