update pricing table name and cols
FlipsideCrypto/solana-models pull request #503
Opened 2024-03-04 22:46 UTC by tarikceric

Update gold price tables to follow the standard naming of other chains, and add decimals per customer ask. Naming changes include:

- fact/ez_token_prices_hourly -> fact/ez_hourly_token_prices (and PK renamed)
- recorded_hour -> hour
- close -> price

2024-03-05 15:41 UTC, desmond-hui requested changes

2024-03-05 15:41 UTC, desmond-hui commented on models/silver/prices/silver__token_prices_coin_market_cap_hourly.sql
> -            'prices_v2'
The old source should be removed from `sources.yml` as well?

2024-03-05 15:41 UTC, desmond-hui commented on models/gold/price/price__fact_hourly_token_prices.sql
> +UNION
Should this be a `UNION ALL`?

2024-03-05 15:41 UTC, desmond-hui commented on models/silver/prices/silver__token_prices_coin_market_cap_hourly.sql
> +            'legacy_prices'
This source does not exist in `sources.yml`

2024-03-05 17:11 UTC, tarikceric commented on models/gold/price/price__fact_hourly_token_prices.sql
> +UNION
updated

2024-03-05 17:13 UTC, tarikceric commented on models/silver/prices/silver__token_prices_coin_market_cap_hourly.sql
> -            'prices_v2'
yup old source can be removed since not used anywhere - updated

2024-04-30 14:15 UTC, desmond-hui approved these changes

2024-04-30 14:35 UTC, desmond-hui approved these changes

2024-05-01 19:59 UTC, eric-laurello approved these changes

2024-05-01 20:01 UTC, merged