add solsniper to nft sales
FlipsideCrypto/solana-models pull request #505
Opened 2024-03-08 17:37 UTC by tarikceric

2024-03-11 14:39 UTC, desmond-hui requested changes

2024-03-11 14:39 UTC, desmond-hui commented on models/silver/nfts/silver__nft_sales_solsniper.sql
> +        AND event_type = 'executeSolNftOrder'
We are missing NFT sales both regular and `cNFT` (not sure if latter is supposed to be included or not) as there are more than one NFT sales events.

```
select distinct event_type
from solana.silver.decoded_instructions_combined
where program_id = 'SNPRohhBurQwrpwAptw1QYtpFdfEKitr4WSJ125cN1g'
order by 1;
```

Example: `buyTensorPoolListingV1`

2024-03-13 19:10 UTC, tarikceric commented on models/silver/nfts/silver__nft_sales_solsniper.sql
> +        AND event_type = 'executeSolNftOrder'
added the missing events, via a table+view since these events are deprecated

2024-03-15 15:47 UTC, desmond-hui requested changes

2024-03-15 15:47 UTC, desmond-hui commented on models/silver/nfts/silver__nft_sales_solsniper.sql
> +    AND A.block_timestamp :: DATE >= '2023-05-02'
So, this is something across all our models using decoded data as our base...but I don't think it's appropriate to predicate on `_inserted_timestamp`

We are going to miss transfers due to backfills. I think we need to join based on `block_timestamp::date and tx_id`

I think we can/should generate the contiguous block_timestamp ranges of our decoded subset and use that predicate here

2024-03-15 16:20 UTC, desmond-hui requested changes

2024-03-15 16:20 UTC, desmond-hui commented on models/silver/nfts/silver__nft_sales_solsniper.sql
> +    group by 1,2,3,4,5,6,7,8,9,10
Also something to consider here...do we want to left join to transfers instead? What do we want to represent in the model?

- Do we want nft sales where we are able to create a "complete" record? AKA some nft sales will be missing in the output

OR

- Do we always want to capture what we deem as a sale via decoded data in the output? AKA some records may not have sales amount

2024-03-15 16:30 UTC, desmond-hui commented on models/silver/nfts/silver__nft_sales_solsniper.sql
> +    group by 1,2,3,4,5,6,7,8,9,10
Also depending on your answer here...we may want to add a [`relationship` test](https://github.com/dbt-labs/dbt-utils?tab=readme-ov-file#relationships_where-source) in our upstream

2024-03-15 20:55 UTC, tarikceric commented on models/silver/nfts/silver__nft_sales_solsniper.sql
> +    AND A.block_timestamp :: DATE >= '2023-05-02'
logic updated

2024-03-15 22:23 UTC, tarikceric commented on models/silver/nfts/silver__nft_sales_solsniper.sql
> +    group by 1,2,3,4,5,6,7,8,9,10
I like the second options approach of getting everything considered a sale. I was on the fence on whether something should be represented as a true sale if there are no transfers/sales amount, but I suppose if the program is identifying it as a sale it should be in there whether or not there was an exchange of tokens.

Updated to use left join. Not exactly sure how we want to do the relationship test

2024-03-16 16:40 UTC, desmond-hui requested changes

2024-03-16 16:40 UTC, desmond-hui commented on models/silver/nfts/silver__nft_sales_solsniper.sql
> +{% set incr = "" %}
this is older code style, it would be better to make this a set so we don't need to do string concat 

Example
```
{% set abc %}
  create or replace table abc as 
  select * 
  from {{ ref('silver__events') }}
  limit 1
{% endset %}
{% do run_query(abc) %}
```

2024-03-16 16:40 UTC, desmond-hui commented on models/silver/nfts/silver__nft_sales_solsniper.sql
> +    group by 1,2,3,4,5,6,7,8,9,10
I think you can start by trying to provided test from dbt_utils. Example below, unsure if `field` can be multiple keys like `tx_id, index, inner_index`

```
- dbt_utils.relationships_where:
              to: ref('nft_sales_solsniper')
              field: tx_id
              from_condition: program_id = 'sol_sniper_program_id' and event_type in ('my sales events') and _inserted_timestamp >= current_date - 2
              to_condition: _inserted_timestamp >= current_date - 2
```

2024-03-18 19:18 UTC, tarikceric commented on models/silver/nfts/silver__nft_sales_solsniper.sql
> +    group by 1,2,3,4,5,6,7,8,9,10
Thanks for the great idea. This definitely seems like the appropriate check to make sure the solsniper model is returning everything identified as a sale. Updated the yml for decoded_instructions_combined

2024-03-19 14:34 UTC, tarikceric commented on models/silver/nfts/silver__nft_sales_solsniper.sql
> +{% set incr = "" %}
updated

2024-03-19 16:11 UTC, desmond-hui requested changes

2024-03-19 16:11 UTC, desmond-hui commented on models/silver/nfts/silver__nft_sales_solsniper.sql
> +    silver.decoded_instructions_combined
you can use `ref` here

2024-03-19 16:11 UTC, desmond-hui commented on models/silver/nfts/silver__nft_sales_solsniper.sql
> +    {{ ref('silver__nft_sales_solsniper_v1_events_view') }}
I don't think we should be unioning a static view for every incremental load?

2024-03-19 16:26 UTC, tarikceric commented on models/silver/nfts/silver__nft_sales_solsniper.sql
> +    silver.decoded_instructions_combined
updated

2024-03-19 16:26 UTC, tarikceric commented on models/silver/nfts/silver__nft_sales_solsniper.sql
> +    {{ ref('silver__nft_sales_solsniper_v1_events_view') }}
updated to only run if not an incremental

2024-03-19 16:32 UTC, desmond-hui commented on models/silver/nfts/silver__nft_sales_solsniper.sql
> +    {{ ref('silver__nft_sales_solsniper_v1_events_view') }}
Won't the `_inserted_timestamp` be all weird? The max `_inserted_timestamp` will be the max of your incremental subset and this view after the first run. If the max on the view is > than the max of the subset then it wouldn't work?

I guess why have this view in here at all vs. only including it in `models/gold/nft/nft__fact_nft_sales.sql`?

2024-03-19 16:45 UTC, desmond-hui approved these changes

2024-03-19 17:55 UTC, merged