update idl table
FlipsideCrypto/solana-models pull request #537
Opened 2024-04-16 15:06 UTC by tarikceric

- Include additional information in the gold IDL table. Based on user requests for more visibility on decoding process

2024-04-16 16:36 UTC, desmond-hui requested changes

2024-04-16 16:36 UTC, desmond-hui commented on models/silver/idls/silver__idl.sql
> +        solana_dev.information_schema.views
Can remove `solana_dev`

2024-04-16 16:36 UTC, desmond-hui commented on models/silver/idls/silver__idl.sql
> +        ELSE 'not started'
Not sure @eric-laurello @tarikceric thoughts on this but I am leaning we should make these have `_` instead of space (i.e. `in_progress`)

2024-04-16 16:36 UTC, desmond-hui commented on models/silver/idls/silver__idl.sql
I think the table should be named `silver.idls`? To be consistent with our other tables which are all plural AFAIK

Same for the core model...except not sure what change management process we want to use for that since it is existing

2024-04-16 16:36 UTC, desmond-hui commented on models/silver/idls/silver__idl.sql
> +        table_name LIKE 'DECODED_INSTRUCTIONS_BACKFILL_%'
@eric-laurello @tarikceric  Since we have two types of backfills, do we want to exclude retry backfills where we are mostly using it for when IDLs are updated?

2024-04-16 16:36 UTC, desmond-hui commented on models/silver/idls/silver__idl.sql
> +        table_name DESC
I don't think this order by is necessary

2024-04-16 16:36 UTC, desmond-hui commented on models/silver/idls/silver__idl.sql
> +    OR d.earliest_decoded_block IS NULL
Could potentially have some conflict here where the backfill status flag is changed but the earliest block is unchanged, the model would not pick up any other status or column changes. Also another example would be if an IDL is updated, the `idl_hash` would change but it probably would never be updated in this model due to this condition.

An inline `IFF` might work better here

2024-04-16 16:36 UTC, desmond-hui commented on models/silver/idls/silver__idl.yml
> +      - name: IDL_HASH
Why was description removed here for `IDL_HASH`?

2024-04-16 19:41 UTC, tarikceric commented on models/silver/idls/silver__idl.sql
> +        ELSE 'not started'
agreed that seems more standard

2024-04-16 19:44 UTC, tarikceric commented on models/silver/idls/silver__idl.sql
> +        table_name LIKE 'DECODED_INSTRUCTIONS_BACKFILL_%'
will exclude RETRY backfills

2024-04-16 19:47 UTC, tarikceric commented on models/silver/idls/silver__idl.sql
That makes sense, I'll update that after finalized so the comments arent lost from 'deleting' the existing table in the pr. I'll reach out to Liz on the communication for name changes

2024-04-16 21:19 UTC, tarikceric commented on models/silver/idls/silver__idl.sql
> +    OR d.earliest_decoded_block IS NULL
ended up adding a union under the incremental, because i would want to use the existing 'earliest_block_decoded' if it just a idl_hash change or there's a backfill occurring but earliest block is unchanged -- what do you think of that approach?

2024-04-16 21:54 UTC, tarikceric commented on models/silver/idls/silver__idl.yml
> +      - name: IDL_HASH
accidently removed it, good catch

2024-04-18 14:47 UTC, desmond-hui requested changes

2024-04-18 14:47 UTC, desmond-hui commented on models/silver/idls/silver__idl.sql
> +    OR d.earliest_decoded_block IS NULL
That seems too complicated. I think you can use `iff` for the column itself and remove the WHERE clause and leave everything else the same as before

```
{% if is_incremental() %}
        iff(b.earliest_decoded_block < d.earliest_decoded_block, b.earliest_decoded_block, d.earliest_decoded_block) AS earliest_decoded_block,
        {% else %}
        b.earliest_decoded_block,
        {% endif %}
```

2024-04-18 14:47 UTC, desmond-hui commented on models/silver/idls/silver__idl.sql
> +        WHEN earliest_decoded_block = first_block_id AND in_progress_program_id IS NOT NULL THEN 'complete'
Why are we checking for `in_progress_program_id IS NOT NULL` here? Wouldn't `in_progress_program_id` be NULL when the backfill is `complete`?

2024-04-18 14:48 UTC, desmond-hui commented on models/silver/idls/silver__idl.sql
> +    OR d.earliest_decoded_block IS NULL
That seems too complicated. I think you can use `iff` for the column itself and remove the WHERE clause and leave everything else the same as before

```
{% if is_incremental() %}
        iff(b.earliest_decoded_block < d.earliest_decoded_block, b.earliest_decoded_block, d.earliest_decoded_block) AS earliest_decoded_block,
        {% else %}
        b.earliest_decoded_block,
        {% endif %}
```

2024-04-18 14:51 UTC, desmond-hui commented on models/gold/core/core__dim_idl.sql
> +    _inserted_timestamp,
Do we want to expose `_inserted_timestamp` in gold layer?

2024-04-18 15:26 UTC, tarikceric commented on models/silver/idls/silver__idl.sql
> +    OR d.earliest_decoded_block IS NULL
sounds good, updated to use that approach

2024-04-18 15:27 UTC, tarikceric commented on models/silver/idls/silver__idl.sql
> +        WHEN earliest_decoded_block = first_block_id AND in_progress_program_id IS NOT NULL THEN 'complete'
My mistake, I was thinking about when we do retry backfills but we're excluding that

2024-04-18 15:44 UTC, desmond-hui commented on models/gold/core/core__dim_idl.sql
> +    _inserted_timestamp,
Lets rename it

2024-04-18 15:54 UTC, desmond-hui approved these changes

2024-04-18 15:54 UTC, desmond-hui commented on models/gold/core/core__dim_idl.yml
> +        description: "{{ doc('backfill_status') }}"
Add description for `date_submitted`

2024-04-18 15:54 UTC, desmond-hui commented on models/gold/core/core__dim_idl.sql
> +    _inserted_timestamp,
Lets rename it

2024-04-18 17:12 UTC, merged