An 4769/me solsniper cnft sales
FlipsideCrypto/solana-models pull request #540
Opened 2024-04-23 14:16 UTC by tarikceric

cNFT sales for solsniper/magic eden
- first get all sales via `_onchain` models, then decode mint via `bronze_api` models, and join into final table

2024-04-23 16:52 UTC, desmond-hui requested changes

2024-04-23 16:52 UTC, desmond-hui commented on models/silver/nfts/silver__nft_sales_solsniper_cnft_onchain.yml
> +          - not_null
Add the included or custom relationship test to make sure all our onchain events make it to the destination table

2024-04-23 16:52 UTC, desmond-hui commented on models/silver/nfts/silver__nft_sales_solsniper_cnft.sql
> +    b.mint IS NOT NULL
I think we should include all the sales, even if we don't have the mint. Add a test to check for NULL mints so we are alerted and can triage the pipeline

2024-04-23 20:57 UTC, tarikceric commented on models/silver/nfts/silver__nft_sales_solsniper_cnft_onchain.yml
> +          - not_null
added relationship test for solsniper and magic_eden_cnft_onchain to decoded_instructions_combined -- or were you thinking a relationship between the `_cnft_onchain` and final `_cnft` table?

2024-04-23 20:58 UTC, tarikceric commented on models/silver/nfts/silver__nft_sales_solsniper_cnft.sql
> +    b.mint IS NOT NULL
removed filter from both models. I think the `not_null` test for the `mint` column in the yml should suffice as a check

2024-04-24 14:01 UTC, desmond-hui requested changes

2024-04-24 14:01 UTC, desmond-hui commented on models/silver/nfts/silver__nft_sales_magic_eden_cnft.sql
How would this (and the solsniper model) "auto-heal"? Meaning, at this moment we now have N records w/ NULL mints because we are waiting for a backfill of the bronze data. How do we fix the NULL records as the bronze data arrives?

2024-04-24 20:36 UTC, tarikceric commented on models/silver/nfts/silver__nft_sales_magic_eden_cnft.sql
great point -- added temp backfill logic using an _inserted_timestamp from bronze table, using a temp `mint_inserted_timestamp` column to track the latest records that have went through the parser

2024-04-25 17:11 UTC, desmond-hui approved these changes

2024-04-25 17:41 UTC, merged