An 4825/raydium swaps
FlipsideCrypto/solana-models pull request #565
Opened 2024-05-22 18:33 UTC by tarikceric

New swaps models for Raydium using decoded instructions

- FR on dev-2xl
```
22:01:40  3 of 3 OK created sql incremental model silver.swaps_intermediate_raydium_stable  [SUCCESS 1 in 269.03s]
22:06:07  2 of 3 OK created sql incremental model silver.swaps_intermediate_raydium_clmm . [SUCCESS 1 in 535.87s]
22:23:38  1 of 3 OK created sql incremental model silver.swaps_intermediate_raydium_amm .. [SUCCESS 1 in 1586.88s]
```
- test
```
18:33:01  Finished running 61 tests, 11 hooks in 0 hours 3 minutes and 33.46 seconds (213.46s).
18:33:02  Completed successfully
18:33:02  Done. PASS=61 WARN=0 ERROR=0 SKIP=0 TOTAL=61
```

2024-05-24 15:06 UTC, desmond-hui requested changes

2024-05-24 16:19 UTC, tarikceric commented on models/silver/swaps/silver__swaps_intermediate_raydium_amm.sql
> +            WHEN temp_user_source_owner IS NOT NULL then silver.udf_get_account_pubkey_by_name('userSourceOwner', decoded_instruction:accounts)
good catch, updated

2024-05-24 19:19 UTC, tarikceric commented on models/silver/swaps/silver__swaps_intermediate_raydium_amm.sql
> +        END AS program_source_token_account,
updated

2024-05-24 19:32 UTC, tarikceric commented on models/silver/swaps/silver__swaps_intermediate_raydium_amm.sql
> +        )
added comments

2024-05-24 19:36 UTC, tarikceric commented on models/silver/swaps/silver__swaps_intermediate_raydium_amm.yml
> +          - not_null: *recent_date_filter
added to `amm` and `stable`

2024-05-28 16:37 UTC, desmond-hui approved these changes

2024-05-30 20:53 UTC, merged