balance models
FlipsideCrypto/solana-models pull request #585
Opened 2024-06-13 06:44 UTC by tarikceric

2024-06-20 16:54 UTC, desmond-hui requested changes

2024-06-20 16:54 UTC, desmond-hui commented on models/silver/balances/silver__token_balances.sql
> +        OUTER JOIN post b
nit: formatting

Should be 
```
FROM
  pre A
FULL OUTER JOIN
  post B

2024-06-20 16:54 UTC, desmond-hui commented on models/silver/balances/silver__token_balances.yml
> +          - not_null: *recent_date_filter
Remove recent date filter on `_inserted_timestamp` tests

2024-06-20 16:54 UTC, desmond-hui commented on models/silver/balances/silver__token_balances.yml
> +      - name: MODIFIED_TIMESTAMP
missing columns definition for `INSERTED_TIMESTAMP`

2024-06-20 16:54 UTC, desmond-hui commented on models/silver/balances/silver__sol_balances.yml
> +      - name: MODIFIED_TIMESTAMP
missing columns definition for `INSERTED_TIMESTAMP`

2024-06-20 16:54 UTC, desmond-hui commented on models/silver/balances/silver__sol_balances.yml
> +      - name: _INSERTED_TIMESTAMP
Remove recent date filter on `_inserted_timestamp` tests

2024-06-20 16:54 UTC, desmond-hui commented on models/gold/core/core__fact_token_balances.sql
> +)
Should the underlying be clustered on `modified_timestamp` instead of `_inserted_timestamp`?

2024-06-20 16:54 UTC, desmond-hui commented on models/gold/core/core__fact_sol_balances.sql
> +    modified_timestamp >= (
Should the underlying be clustered on `modified_timestamp` instead of `_inserted_timestamp`?

2024-06-20 16:54 UTC, desmond-hui commented on models/descriptions/balances/balances.md
> +The final owner of the token account in the transaction.
This is incorrect for the gold layer table. It would be the final owner of the token account in the `block`

2024-06-20 23:47 UTC, tarikceric commented on models/silver/balances/silver__token_balances.yml
> +          - not_null: *recent_date_filter
removed

2024-06-20 23:49 UTC, tarikceric commented on models/silver/balances/silver__token_balances.yml
> +      - name: MODIFIED_TIMESTAMP
added

2024-06-20 23:49 UTC, tarikceric commented on models/silver/balances/silver__sol_balances.yml
> +      - name: MODIFIED_TIMESTAMP
added

2024-06-20 23:49 UTC, tarikceric commented on models/silver/balances/silver__sol_balances.yml
> +      - name: _INSERTED_TIMESTAMP
removed

2024-06-20 23:50 UTC, tarikceric commented on models/gold/core/core__fact_token_balances.sql
> +)
good catch, updated

2024-06-20 23:51 UTC, tarikceric commented on models/gold/core/core__fact_sol_balances.sql
> +    modified_timestamp >= (
updated

2024-06-20 23:55 UTC, tarikceric commented on models/descriptions/balances/balances.md
> +The final owner of the token account in the transaction.
added 'token_balances_block_owner' to use in gold

2024-06-20 23:56 UTC, tarikceric commented on models/silver/balances/silver__token_balances.sql
> +        OUTER JOIN post b
cleaned

2024-06-21 13:43 UTC, desmond-hui requested changes
Have some concerns about the core token balances table run time, but otherwise good work!

2024-06-21 13:43 UTC, desmond-hui commented on models/silver/idls/silver__verified_user_idls.sql
> +        AND block_timestamp::date between  '2024-04-10' and '2024-04-26'
unintended change?

2024-06-21 15:44 UTC, tarikceric commented on models/silver/idls/silver__verified_user_idls.sql
> +        AND block_timestamp::date between  '2024-04-10' and '2024-04-26'
yes...good catch, i was working on getting some unrelated idl verified

2024-06-21 17:14 UTC, desmond-hui approved these changes

2024-06-21 19:27 UTC, merged