An 4929/convert gold views and add SO
FlipsideCrypto/solana-models pull request #611
Opened 2024-07-17 20:36 UTC by tarikceric

Search optimization and clustering for `core`, `defi`, and `price` schema

1. For views with union/join logic, convert to table
   - `fact_swaps`, `fact_liquidity_pool_actions`, and `fact_stake_pool_actions`
2. For views selecting directly from a single silver table, add SO and clustering

SO methodology: https://docs.google.com/document/d/1ijtzwOZ21ILKD_X4Vghu7YrFvKfOWT897g8CQTpbWSk/edit

2024-07-18 16:47 UTC, desmond-hui reviewed
Can you include incremental times from your dev runs?

The underlying isnt clustered by `modified_timestamp` so wouldn't these do full scans?

2024-07-24 16:47 UTC, desmond-hui requested changes

2024-07-24 16:47 UTC, desmond-hui commented on models/gold/defi/defi__fact_swaps.sql
> +    modified_timestamp::date < '2024-06-09'
nit: set it as a jinja variable then reference the var instead.

2024-07-24 16:47 UTC, desmond-hui commented on models/silver/swaps/bonkswap/silver__swaps_intermediate_bonkswap.sql
> +    cluster_by = ['block_timestamp::DATE','modified_timestamp::DATE'],
We shouldn't change these since the downstream is `silver__swaps` and not the gold layer?

2024-07-24 16:47 UTC, desmond-hui commented on models/silver/swaps/dooar/silver__swaps_intermediate_dooar.sql
> +    cluster_by = ['block_timestamp::DATE','modified_timestamp::DATE'],
We shouldn't change these since the downstream is `silver__swaps` and not the gold layer?

2024-07-24 16:47 UTC, desmond-hui commented on models/silver/swaps/jupiter/v6/silver__swaps_intermediate_jupiterv6_2.sql
> +    cluster_by = ['block_timestamp::DATE','modified_timestamp::DATE'],
We shouldn't change these since the downstream is `silver__swaps` and not the gold layer?

2024-07-24 16:47 UTC, desmond-hui commented on models/silver/swaps/meteora/silver__swaps_intermediate_meteora.sql
> +    cluster_by = ['block_timestamp::DATE','modified_timestamp::DATE'],
We shouldn't change these since the downstream is `silver__swaps` and not the gold layer?

2024-07-24 16:47 UTC, desmond-hui commented on models/silver/swaps/phoenix/silver__swaps_intermediate_phoenix.sql
> +    cluster_by = ['block_timestamp::DATE','modified_timestamp::DATE'],
We shouldn't change these since the downstream is `silver__swaps` and not the gold layer?

2024-07-24 16:47 UTC, desmond-hui commented on models/silver/swaps/raydium/silver__swaps_intermediate_raydium_clmm.sql
> +    cluster_by = ['block_timestamp::DATE','modified_timestamp::DATE'],
We shouldn't change these since the downstream is `silver__swaps` and not the gold layer?

2024-07-24 16:47 UTC, desmond-hui commented on models/silver/swaps/raydium/silver__swaps_intermediate_raydium_stable.sql
> +    cluster_by = ['block_timestamp::DATE','modified_timestamp::DATE'],
We shouldn't change these since the downstream is `silver__swaps` and not the gold layer?

2024-07-24 16:47 UTC, desmond-hui commented on models/silver/swaps/raydium/silver__swaps_intermediate_raydium_v4_amm.sql
> +    cluster_by = ['block_timestamp::DATE','modified_timestamp::DATE'],
We shouldn't change these since the downstream is `silver__swaps` and not the gold layer?

2024-07-24 22:38 UTC, tarikceric commented on models/gold/defi/defi__fact_swaps.sql
> +    modified_timestamp::date < '2024-06-09'
updated

2024-07-24 22:41 UTC, tarikceric commented on models/silver/swaps/bonkswap/silver__swaps_intermediate_bonkswap.sql
> +    cluster_by = ['block_timestamp::DATE','modified_timestamp::DATE'],
These actually dont land in silver__swaps, only the `intermediate_generic`/`jupiterv4`/`orca` do. When the first model was made off decoded events we decided not to add those into the silver__swaps

2024-07-25 13:37 UTC, desmond-hui approved these changes

2024-08-05 20:18 UTC, merged