An 5088/gold optimization 2
FlipsideCrypto/solana-models pull request #636
Opened 2024-08-14 02:43 UTC by tarikceric

Search optimization and clustering for NFT and GOV schema

1. For larger/complex core views with union/join logic, convert to table and update silver clustering
- add logic to select from legacy views only during FR
- includes: `gov.fact_stake_accounts`, `gov.fact_validators`, `gov.fact_vote_accounts`, `nft.fact_nft_sales`)

3. For views with simpler logic, add SO and clustering to silver references

FR successful for core tables:
```
-- 23:47:48  2 of 5 OK created sql incremental model gov.fact_validators .................... [SUCCESS 1 in 23.25s]
-- 23:47:53  3 of 5 OK created sql incremental model gov.fact_vote_accounts ................. [SUCCESS 1 in 28.33s]
-- 23:48:27  4 of 5 OK created sql incremental model nft.fact_nft_sales ..................... [SUCCESS 1 in 61.76s]
-- 23:48:37  1 of 5 OK created sql incremental model gov.fact_stake_accounts ................ [SUCCESS 1 in 71.95s]
```

2024-08-14 15:19 UTC, desmond-hui requested changes

2024-08-14 15:19 UTC, desmond-hui commented on models/gold/gov/gov__fact_validators.sql
> +    tags = ['scheduled_non_core','exclude_change_tracking']
I think this only excluded change tracking because it was a view with join/union. We should be able to enable it now that it is a table

2024-08-14 15:19 UTC, desmond-hui commented on models/gold/nft/nft__fact_nft_sales.sql
> +    cluster_by = ['block_timestamp::DATE','marketplace','is_compressed','program_id'],
seems...odd that we woudl have both marketplace and program_id in the cluster key. Arent they are 1 to 1 relation?

2024-08-14 15:19 UTC, desmond-hui commented on models/gold/nft/nft__fact_nft_sales.sql
> +        ['tx_id']
Reason that some of these are `tx_id` some are `[tx_id, mint]`?

2024-08-14 16:28 UTC, tarikceric commented on models/gold/nft/nft__fact_nft_sales.sql
> +    cluster_by = ['block_timestamp::DATE','marketplace','is_compressed','program_id'],
Yup youre correct, but was assuming a user might query by `marketplace` instead of `program_id` so added it in. Is it not necessary then?

2024-08-14 16:44 UTC, tarikceric commented on models/gold/nft/nft__fact_nft_sales.sql
> +        ['tx_id']
Just based off our existing logic for the view and silver tables so assume that's the unique id that was decided for when the model was made

ie. There are silver nft_sales_xxx models that are just tx_id (ie silver__nft_sales_magic_eden_v2) so used that in the view. 

But good point bc there are models like solanart where silver uses tx_id + mint but the view only used tx_id.

Should i make the view column consistent with what the corresponding silver models are using for the _id? or adjust the ones only using tx_id to also include mint? Theres then also tensorswap which uses `['tx_id','mint','purchaser']`

2024-08-14 16:52 UTC, desmond-hui commented on models/gold/nft/nft__fact_nft_sales.sql
> +    cluster_by = ['block_timestamp::DATE','marketplace','is_compressed','program_id'],
I am just not sure it's worth clustering by 2 keys that are essentially the same...probably put one in SO instead?

2024-08-14 16:55 UTC, desmond-hui commented on models/gold/nft/nft__fact_nft_sales.sql
> +        ['tx_id']
Make the view consistent with the corresponding silver model. Are there any **active** marketplaces where we are only using `tx_id`?

2024-08-16 14:52 UTC, tarikceric commented on models/gold/nft/nft__fact_nft_sales.sql
> +    cluster_by = ['block_timestamp::DATE','marketplace','is_compressed','program_id'],
yea that makes sense to me, moved marketplace to SO

2024-08-16 14:57 UTC, tarikceric commented on models/gold/nft/nft__fact_nft_sales.sql
> +        ['tx_id']
`silver__nft_sales_magic_eden_v2` is the one active model that only uses tx_id

2024-08-16 15:03 UTC, desmond-hui commented on models/gold/nft/nft__fact_nft_sales.sql
> +        ['tx_id']
Whats the effort to change that to `tx_id, mint`? I feel like it should be more specific than just tx_id. Are there really no txs with more than one NFT sale for ME2?

2024-08-16 15:29 UTC, tarikceric commented on models/gold/nft/nft__fact_nft_sales.sql
> +        ['tx_id']
I suppose could do an ad-hoc query to update that col to use `tx_id+mint`, and just update the silver model logic. It seems like it really is just one nft sale per tx 

`select count(distinct(tx_id)),count(*) from solana.silver.nft_sales_magic_eden_v2;`

2024-08-16 15:48 UTC, desmond-hui approved these changes

2024-08-19 13:47 UTC, merged