An 4528/events inner
FlipsideCrypto/solana-models pull request #655
Opened 2024-09-13 14:10 UTC by tarikceric

- create events_inner silver and gold tables
- run backfill via dbt_run_batch_backfill_2 and update model tags upon completion

backfill incremental runs on 2xl (5 day batch):
```
16:38:18  1 of 2 START sql incremental model silver.events_inner ......................... [RUN]
16:44:26  1 of 2 OK created sql incremental model silver.events_inner .................... [SUCCESS 775892786 in 367.76s]
16:44:26  2 of 2 START sql incremental model core.fact_events_inner ...................... [RUN]
16:49:48  2 of 2 OK created sql incremental model core.fact_events_inner ................. [SUCCESS 775892786 in 322.69s]
```

backfill incremental runs on 2xl (12hr batch)
```
16:06:50  1 of 2 START sql incremental model silver.events_inner ......................... [RUN]
16:08:35  1 of 2 OK created sql incremental model silver.events_inner .................... [SUCCESS 228560663 in 105.14s]
16:08:35  2 of 2 START sql incremental model core.fact_events_inner ...................... [RUN]
16:10:15  2 of 2 OK created sql incremental model core.fact_events_inner ................. [SUCCESS 228560663 in 99.98s]
```

tests (recency only failure in silver):
`14:10:14  Done. PASS=36 WARN=0 ERROR=1 SKIP=0 TOTAL=37`

2024-09-13 14:27 UTC, desmond-hui commented
> incremental runs on dev-2xl:
> 
> ```
> 13:44:05  1 of 2 OK created sql incremental model silver.events_inner .................... [SUCCESS 50034810 in 126.11s]
> 13:44:05  2 of 2 START sql incremental model core.fact_events_inner ...................... [RUN]
> 13:50:58  2 of 2 OK created sql incremental model core.fact_events_inner ................. [SUCCESS 1 in 412.33s]
> ```

Why does gold take so much longer than silver?

2024-09-13 14:31 UTC, desmond-hui requested changes

2024-09-13 14:31 UTC, desmond-hui commented on macros/helpers/helpers.sql
>          {{ "and _inserted_timestamp between (select max(_inserted_timestamp) from " ~ model_name ~ ") and (select dateadd('hour',4,max(_inserted_timestamp)) from " ~ model_name ~ ")" }}
These look like the same predicates for both conditions?

2024-09-13 14:31 UTC, desmond-hui commented on models/gold/core/core__fact_events_inner.yml
> +          - dbt_expectations.expect_column_to_exist
This test should probably be for all columns in gold table

2024-09-13 14:31 UTC, desmond-hui commented on models/gold/core/core__fact_events_inner.yml
> +          - not_null: *recent_date_filter
Can't use filter here, test never fails w/ the filter

2024-09-13 14:31 UTC, desmond-hui commented on models/silver/silver__events_inner.sql
> +{% endif %}
nit: indents

2024-09-13 14:31 UTC, desmond-hui commented on models/silver/silver__events_inner.sql
> +    unique_key = ['events_inner_id'],
if you are using the surrogate key as the merge key then it needs to be part of SO

2024-09-13 14:31 UTC, desmond-hui commented on models/silver/silver__events_inner.sql
> +    post_hook = enable_search_optimization('{{this.schema}}','{{this.identifier}}','ON EQUALITY(tx_id, program_id, event_type, inner_instruction_program_ids)'),
`inner_instruction_program_ids` doesnt exist

2024-09-13 14:31 UTC, desmond-hui commented on models/silver/silver__events_inner.yml
> +              name: test_silver__not_null_inner_instructions_invocation_id
rename

2024-09-13 14:31 UTC, desmond-hui commented on models/gold/core/core__fact_events_inner.sql
> +    cluster_by = ['block_timestamp::DATE','modified_timestamp::DATE'],
Do we have downstream dependencies for this table such that it warrants clustering by `modified_timestamp`?

2024-09-13 14:31 UTC, desmond-hui commented on models/gold/core/core__fact_events_inner.sql
> +    unique_key = ['fact_events_inner_id'],
if you are using the surrogate key as the merge key then it needs to be part of SO

2024-09-13 14:31 UTC, desmond-hui commented on macros/helpers/helpers.sql
> +    {% elif max_date >= '2022-09-01' and max_date < '2022-09-05' %}
I think this change needs to be tested more thoroughly, data in dev is only up to `2022-08-16 15:56:31.000`.

2024-09-16 15:57 UTC, tarikceric commented on macros/helpers/helpers.sql
>          {{ "and _inserted_timestamp between (select max(_inserted_timestamp) from " ~ model_name ~ ") and (select dateadd('hour',4,max(_inserted_timestamp)) from " ~ model_name ~ ")" }}
slightly different -- the new one is for everything before '2022-09-01' because the data before then is still large so breaking it up

2024-09-16 16:00 UTC, tarikceric commented
> > incremental runs on dev-2xl:
> > ```
> > 13:44:05  1 of 2 OK created sql incremental model silver.events_inner .................... [SUCCESS 50034810 in 126.11s]
> > 13:44:05  2 of 2 START sql incremental model core.fact_events_inner ...................... [RUN]
> > 13:50:58  2 of 2 OK created sql incremental model core.fact_events_inner ................. [SUCCESS 1 in 412.33s]
> > ```
> 
> Why does gold take so much longer than silver?

my fault, i ran the initial run for gold after a few incrementals of the silver so it was basically the fr -- will update with correct incremental

2024-09-16 16:04 UTC, tarikceric commented on models/gold/core/core__fact_events_inner.yml
> +          - not_null: *recent_date_filter
removed filter

2024-09-16 16:09 UTC, tarikceric commented on models/silver/silver__events_inner.sql
> +{% endif %}
cleaned up

2024-09-16 16:10 UTC, tarikceric commented on models/silver/silver__events_inner.sql
> +    unique_key = ['events_inner_id'],
is there a preference to using the surrogate key for the merge vs the individual columns?

2024-09-16 16:11 UTC, tarikceric commented on models/silver/silver__events_inner.sql
> +    post_hook = enable_search_optimization('{{this.schema}}','{{this.identifier}}','ON EQUALITY(tx_id, program_id, event_type, inner_instruction_program_ids)'),
updated with instruction_program_id

2024-09-16 16:11 UTC, tarikceric commented on models/silver/silver__events_inner.yml
> +              name: test_silver__not_null_inner_instructions_invocation_id
renamed

2024-09-16 16:12 UTC, tarikceric commented on models/gold/core/core__fact_events_inner.sql
> +    cluster_by = ['block_timestamp::DATE','modified_timestamp::DATE'],
nope good point, removed

2024-09-16 16:12 UTC, tarikceric commented on models/gold/core/core__fact_events_inner.sql
> +    unique_key = ['fact_events_inner_id'],
is there a preference to using the surrogate key for the merge vs the individual columns?

2024-09-16 16:14 UTC, tarikceric commented on macros/helpers/helpers.sql
> +    {% elif max_date >= '2022-09-01' and max_date < '2022-09-05' %}
only ran a few incrementals, which would do 4hr batches. I suppose il run incrementals until it gets past 09-05 and it goes 15 day incrementals

2024-09-16 16:46 UTC, desmond-hui commented on models/silver/silver__events_inner.sql
> +    unique_key = ['events_inner_id'],
If any of the individual columns are NULLABLE then we should use the surrogate key

2024-09-16 16:49 UTC, desmond-hui commented on macros/helpers/helpers.sql
>          {{ "and _inserted_timestamp between (select max(_inserted_timestamp) from " ~ model_name ~ ") and (select dateadd('hour',4,max(_inserted_timestamp)) from " ~ model_name ~ ")" }}
Maybe I am not understanding but when I use a text diff finder for both statements it says they are identical.

<img width="1685" alt="Screenshot 2024-09-16 at 9 48 48 AM" src="https://github.com/user-attachments/assets/d71bcfa7-9180-49af-a0d8-9b93a36f9a99">

2024-09-16 16:50 UTC, desmond-hui commented on models/gold/core/core__fact_events_inner.sql
> +    unique_key = ['fact_events_inner_id'],
See: https://github.com/FlipsideCrypto/solana-models/pull/655#discussion_r1761494284

2024-09-17 00:35 UTC, tarikceric commented on macros/helpers/helpers.sql
>          {{ "and _inserted_timestamp between (select max(_inserted_timestamp) from " ~ model_name ~ ") and (select dateadd('hour',4,max(_inserted_timestamp)) from " ~ model_name ~ ")" }}
oh gotcha, yea youre correct -- thought there should be a separate one for `< 2022-09-01`but that's unnecessary. But ended up pdating the macro to do a 12hr range because there arent as many

2024-09-17 00:36 UTC, tarikceric commented on models/silver/silver__events_inner.sql
> +    unique_key = ['events_inner_id'],
updated to use individual cols since they are not nullable

2024-09-17 00:36 UTC, tarikceric commented on models/gold/core/core__fact_events_inner.sql
> +    unique_key = ['fact_events_inner_id'],
updated to use individual cols since they are not nullable

2024-09-18 18:58 UTC, tarikceric commented on macros/helpers/helpers.sql
> +    {% elif max_date >= '2022-09-01' and max_date < '2022-09-05' %}
adjusted backfill logic to account for those gaps

2024-09-19 13:40 UTC, desmond-hui approved these changes

2024-09-19 17:53 UTC, merged