An 5156/jupv4 refactor
FlipsideCrypto/solana-models pull request #672
Opened 2024-10-10 15:58 UTC by tarikceric

Create silver jupv4 tables for individual and aggregated swaps

Missing data:
- truncated logs result in missing txs before 2023-10-31
- Ex query to find missing by date, which seems to be due to issues with truncated logs

```
WITH unmatched_tx AS (
    SELECT a.tx_id, a.block_timestamp
    FROM SOLANA.silver.swaps_intermediate_jupiterv4 a
    LEFT JOIN solana_dev.silver.swaps_inner_intermediate_jupiterv4 b
    ON a.tx_id = b.tx_id
    AND a.block_timestamp::date = b.block_timestamp::date
    WHERE a.block_timestamp::date BETWEEN '2022-07-12' and '2024-09-15'
    AND a.succeeded = TRUE
    AND b.tx_id IS NULL
)
-- select count(*),block_timestamp::date from unmatched_tx
-- group by 2;

SELECT t.*
FROM unmatched_tx t
WHERE EXISTS (
    SELECT 1
    FROM solana.silver.transaction_logs_program_data p
    WHERE p.tx_id = t.tx_id
    AND p.program_id = 'JUP4Fb2cqiRUcaTHdrPC8h2gNsA2ETXiPDD33WcGuJB'
    AND p.block_timestamp::date BETWEEN '2022-07-12' and '2024-09-15'
);
```

possible solution in gold tables
- For `defi.fact_jupiter_summary`, use existing aggregated jupiter v4 swaps from `silver.swaps` before 23/10/31
- For `defi.fact_jupiter_inner`, use existing `silver.swaps_intermediate_jupiterv4` before 23/10/31

TO-DO for gold:
1. exclude jupv4 from `fact_swaps`, which comes from `silver.swaps`. BUT in silver.swaps, we need to keep the jupv4 tx's that need to be used in fact_swaps_jupiter_summary due to missing in silver.swaps_intermediate_jupiterv4_2. 
2. remove `swaps_jupiter_intermediatev5_1` + `5_2` from `defi.fact_swaps` and add to `fact_swaps_jupiter_summary`
3. add `swaps_inner_intermediate_jupiterv5` to `fact_swaps_jupiter_inner`

- Runs
FR on 2xl for inner
`15:57:29  1 of 1 OK created sql incremental model silver.swaps_inner_intermediate_jupiterv4  [SUCCESS 1 in 94.92s]
`
incremental on medium for inner
`18:01:19  1 of 2 OK created sql incremental model silver.swaps_inner_intermediate_jupiterv4  [SUCCESS 856 in 20.09s]
`
incremental on medium for v4_2
`17:58:29  2 of 2 OK created sql incremental model silver.swaps_intermediate_jupiterv4_2 .. [SUCCESS 192731 in 21.18s]`

Tests for both tables(1 error due to recency)
`15:33:20  Done. PASS=31 WARN=0 ERROR=1 SKIP=0 TOTAL=32`

2024-10-10 16:37 UTC, desmond-hui requested changes

2024-10-11 06:12 UTC, tarikceric commented on models/silver/swaps/jupiter/v4/silver__swaps_inner_intermediate_jupiterv4.sql
> +                decoded_instruction :accounts
removed

2024-10-11 06:13 UTC, tarikceric commented on models/silver/swaps/jupiter/v4/silver__swaps_inner_intermediate_jupiterv4.sql
> +{% endif %}
added the NULL swapper logic, and the logic for selecting swaps again for any gaps/issues in the window function

2024-10-11 06:16 UTC, tarikceric commented on models/silver/swaps/jupiter/v4/silver__swaps_intermediate_jupiterv4_2.sql
Yea you were right -- I revamped the logic, based it off v6 but with some differences due to the decoded data, namely:
- v4 events do not have inputIndex/outputIndex in the decoded data so logic is different
- have to deal with 3 different types of decoded instruction data and parsing out the swaps: standard is flatten by swapleg, then splits (ie ones like your example)  that need to be flattened further, and then there's nonroute event_types that seem to always be standalone

2024-10-11 06:23 UTC, tarikceric commented on models/silver/swaps/jupiter/v4/silver__swaps_intermediate_jupiterv4_2.sql
> +    {{ get_batch_load_logic(this,30,'2023-10-08') }}
i was doing some stupid batch loading as an ad-hoc way to test some block ranges so that's probably why it was weird. Kept the batch logic just for now as i haven't been able to consistently backfill with 2xl without it spinning, and most of the new backfilled decoded data is from the last few weeks so need to get it recent to get the complete data.

2024-10-15 02:08 UTC, tarikceric commented on models/silver/swaps/jupiter/v4/silver__swaps_intermediate_jupiterv4_2.sql
> +    {{ get_batch_load_logic(this,30,'2023-10-08') }}
You were right about not needing the batch logic, runs wildly faster now -- fr on 2xl:

`01:33:08  Finished running 1 incremental model, 11 project hooks in 0 hours 2 minutes and 16.66 seconds (136.66s).`

2024-10-29 21:13 UTC, tarikceric commented on models/silver/swaps/jupiter/v4/silver__swaps_intermediate_jupiterv4_2.sql
Updated logic

2024-10-29 21:15 UTC, tarikceric commented
For dealing truncated logs, I created a new boolean column TRUNCATED_LOGS, which we can then filter out into the gold tables

2024-10-29 23:51 UTC, desmond-hui approved these changes

2024-10-30 13:58 UTC, merged