model and workflow
FlipsideCrypto/solana-models pull request #686
Opened 2024-10-31 04:32 UTC by tarikceric

- Model to store updated consume_units for transactions
- set to run 2x every 5 mins based on incrementals below

```
04:19:34  Finished running 1 incremental model, 11 project hooks in 0 hours 2 minutes and 25.83 seconds (145.83s).
04:25:00  Finished running 1 incremental model, 11 project hooks in 0 hours 2 minutes and 21.69 seconds (141.69s).

```

2024-10-31 15:54 UTC, desmond-hui requested changes

2024-10-31 15:54 UTC, desmond-hui commented on models/silver/backfill/silver__transactions_units_consumed.sql
Can we put `backfill` prefix in the model name

2024-10-31 15:54 UTC, desmond-hui commented on models/silver/backfill/silver__transactions_units_consumed.sql
> +    pre_final
This is fine, but any reason this isnt just one query w/o the CTE?

2024-10-31 15:54 UTC, desmond-hui commented on models/silver/backfill/silver__transactions_units_consumed.sql
> +        SELECT max(_partition_id)+1, max(_partition_id)+5 FROM {{ this }}
We should set a global max partition since we are using the value from the node already?

2024-10-31 15:54 UTC, desmond-hui commented on models/silver/backfill/silver__transactions_units_consumed.sql
> +        SELECT 24239, 24239 /* When computeUnitsConsumed first appears in node response */
This goes pretty far back so I would just be on the lookout for large partitions (think times we had to backfill data due to outages or whatever) where this could be an issue.

<img width="1234" alt="Screenshot 2024-10-31 at 8 43 30 AM" src="https://github.com/user-attachments/assets/b74dc1a7-78a8-4bf5-bb57-6a58714b4b59">

I am running this just for partition `103410` and it is taking over 10mins already. I think it's worth it to test it out on a larger machine and find some sort of cutoff in terms of # of records in a partition and handle those separately

2024-10-31 17:46 UTC, tarikceric commented on models/silver/backfill/silver__transactions_units_consumed.sql
renamed

2024-10-31 17:46 UTC, tarikceric commented on models/silver/backfill/silver__transactions_units_consumed.sql
> +    pre_final
simplified it

2024-10-31 17:46 UTC, tarikceric commented on models/silver/backfill/silver__transactions_units_consumed.sql
> +        SELECT max(_partition_id)+1, max(_partition_id)+5 FROM {{ this }}
added

2024-10-31 17:47 UTC, tarikceric commented on models/silver/backfill/silver__transactions_units_consumed.sql
> +        SELECT 24239, 24239 /* When computeUnitsConsumed first appears in node response */
added list of partitions to exclude and run manually after

2024-11-01 14:03 UTC, desmond-hui approved these changes

2024-11-01 16:32 UTC, merged