An 5223/jupiter limit orders
FlipsideCrypto/solana-models pull request #689
Opened 2024-10-31 18:59 UTC by tarikceric

- Add limit order related cols
   - Flag to indicate whether a swap was initiated by Jupiter limit order
   - List the source wallet that requested the limit order if the above is true
   - Add tests for new columns + checks for the specific addresses that Jupiter limit orders use
- Will use FR'ed dev table to update prod
```
UPDATE solana.silver.swaps_intermediate_jupiterv6_2 AS p
SET 
    is_limit_swap = d.is_limit_swap,
    limit_requester = d.limit_requester
FROM solana_dev.silver.swaps_intermediate_jupiterv6_2 AS d
WHERE 
    p.swaps_intermediate_jupiterv6_id = d.swaps_intermediate_jupiterv6_id
    and p.block_timestamp::date >= '2023-10-01'
    and p.is_limit_swap is null;
```

Incremental on Medium
`18:33:15  1 of 1 OK created sql incremental model silver.swaps_intermediate_jupiterv6_2 .. [SUCCESS 215711 in 116.93s]
`
Tests (after running FR on dev)
```
18:24:05  Finished running 25 data tests, 11 project hooks in 0 hours 1 minutes and 6.79 seconds (66.79s).
18:24:05  
18:24:05  Completed successfully
18:24:05  
18:24:05  Done. PASS=25 WARN=0 ERROR=0 SKIP=0 TOTAL=25
```

2024-11-01 14:48 UTC, desmond-hui requested changes

2024-11-01 14:48 UTC, desmond-hui commented on models/silver/swaps/jupiter/v6/silver__swaps_intermediate_jupiterv6_2.sql
> +    i.swapper IN ('{{ jupiter_limit_singers | join("','") }}') AS is_limit_swap,
This seems to be missing a condition. I think it is identifying other swaps done by the swappers that are not flash-fills and probably are not limit swaps?

[Example](https://solscan.io/tx/3cvYA5y9qi96qekV37ZE3EERvmf6isWs7FGowuepnSNkLhPz1SHiJX3E8kbP49y4euyu8Yj5xr8v4msZgzEwLLvg)

Query
```
select *
from solana_dev.silver.swaps_intermediate_jupiterv6_2
where block_timestamp::date >= '2023-10-01'
and is_limit_swap
and limit_requester IS NULL;
```

Should only be counted as a limit request if it is also a flash fill order?

There seems to be a similar interaction with DCA that is unaccounted for, but much less prevalent (< 500 records) vs. `> 1M` records for limit orders. I added a [bug ticket](https://team-1612274056224.atlassian.net/browse/AN-5429) for looking into the DCA records

2024-11-01 14:48 UTC, desmond-hui commented on models/silver/swaps/jupiter/v6/silver__swaps_intermediate_jupiterv6_2.sql
> +    i.swapper IN ('{{ jupiter_limit_singers | join("','") }}') AS is_limit_swap,
I know this is just copy pasted, but this should be `signers` not `singers` 😆

2024-11-05 01:59 UTC, tarikceric commented on models/silver/swaps/jupiter/v6/silver__swaps_intermediate_jupiterv6_2.sql
> +    i.swapper IN ('{{ jupiter_limit_singers | join("','") }}') AS is_limit_swap,
Update here with similar logic as DCA

2024-11-05 02:00 UTC, tarikceric commented on models/silver/swaps/jupiter/v6/silver__swaps_intermediate_jupiterv6_2.sql
> +    i.swapper IN ('{{ jupiter_limit_singers | join("','") }}') AS is_limit_swap,
updated

2024-11-05 02:02 UTC, tarikceric commented
> Member

added `modified_timestamp` change to update statement

2024-11-05 14:58 UTC, desmond-hui approved these changes

2024-11-05 20:28 UTC, merged