An 5449/update jup v4v5 gold
FlipsideCrypto/solana-models pull request #707
Opened 2024-11-12 05:03 UTC by tarikceric

Move jupiter v4 + v5 swaps into Jupiter gold tables
- Jupiter v4
   - truncated logs result in missing txs before 2023-10-31, so have to use existing data for older swaps
   - In `defi.fact_jupiter_summary`, use existing aggregated swaps from `silver.swaps` before 23/10/31
   - In `defi.fact_jupiter_inner`, convert `silver.swaps_intermediate_jupiterv4` into view and use that before 23/10/31
   - In `silver.swaps`, remove jupiter v4 logic moving forward
   - In `fact_swaps`, run delete statement to delete all records using v4 program id
- Jupiter v5
   - remove `swaps_jupiter_intermediatev5_1` + `5_2` from `defi.fact_swaps` and add to `fact_swaps_jupiter_summary`
   - add `swaps_inner_intermediate_jupiterv5` to` fact_swaps_jupiter_inner`

- Column issues:
   - `swaps_intermediate_jupiterv5_1_view` and `v5_2_view` don't contain `index` and `inner index` so these are set to null when added to jupiter_summary
   - The v4 swaps in `silver__swaps` do not contain `swap_index`, `index`, or `inner_index`, so these are set to null when adding the older swaps to `jupiter_summary`

Delete statement to remove v4 + v5 swaps from fact_swaps:
```
delete from solana.defi.fact_swaps
where program_id in ('JUP4Fb2cqiRUcaTHdrPC8h2gNsA2ETXiPDD33WcGuJB',
    'JUP5pEAZeHdHrLxh5UCwAbpjGwYKKoquCpda2hfP4u8',
    'JUP5cHjnnCx2DppVsufsLrXs8EBZeEZzGtEK9Gdz6ow'
);
```

Runs + tests

- view runs (jupiter summary error due to change tracking in dev)
```
04:19:30  2 of 2 ERROR creating sql view model defi.fact_swaps_jupiter_summary ........... [ERROR in 3.32s]
04:19:31  1 of 2 OK created sql view model defi.fact_swaps_jupiter_inner ................. [SUCCESS 1 in 4.10s]
```

- fact_swaps inc runs
```
04:38:38  1 of 1 OK created sql incremental model defi.fact_swaps ........................ [SUCCESS 1744 in 21.30s]
```

- fact_swaps testing
```
04:43:03  Finished running 28 data tests, 7 project hooks in 0 hours 1 minutes and 16.84 seconds (76.84s).
04:43:03  Completed successfully
04:43:03  Done. PASS=28 WARN=0 ERROR=0 SKIP=0 TOTAL=28
```

- silver_swaps run
```
04:44:51  1 of 1 OK created sql incremental model silver.swaps ........................... [SUCCESS 2 in 5.71s]
```

2024-11-12 17:29 UTC, desmond-hui requested changes
For the NULL index/inner_index/swap_index I think the lift is pretty low from what I can tell to get these added.

## v4
Maybe I am missing something here but table looks to have that data available
```
select index, inner_index, swap_index
from solana.silver.swaps_intermediate_jupiterv4
where block_timestamp <= '2023-10-31'
and succeeded
limit 10;
```

## v5
There are no inner instruction swaps here so we can use `swap_index` = index, inner_index = NULL and `swap_index` = row_number() func
```
select tx_id, swap_index
from solana.silver.swaps_intermediate_jupiterv5_1
group by 1,2
having count(*) > 1;

select tx_id, swap_index
from solana.silver.swaps_intermediate_jupiterv5_2
group by 1,2
having count(*) > 1;
```

2024-11-12 17:29 UTC, desmond-hui commented on models/gold/defi/defi__fact_swaps_jupiter_inner.sql
We should remove any `succeeded=FALSE` transactions from this since the v6 data only has successful transactions

2024-11-12 17:29 UTC, desmond-hui commented on models/gold/defi/defi__fact_swaps_jupiter_summary.sql
We should remove any `succeeded=FALSE` transactions from this since the v6 data only has successful transactions

2024-11-12 18:57 UTC, tarikceric commented on models/gold/defi/defi__fact_swaps_jupiter_inner.sql
added to select for jupiterv4_view

2024-11-12 18:57 UTC, tarikceric commented on models/gold/defi/defi__fact_swaps_jupiter_summary.sql
added to select for `silver_swaps`

2024-11-12 18:58 UTC, tarikceric commented
> For the NULL index/inner_index/swap_index I think the lift is pretty low from what I can tell to get these added.
> 
> ## v4
> ~Maybe I am missing something here but table looks to have that data available~ (v4 comes form silver.swaps)
> 
> So these swaps from the older model are summarized to the **transaction** level ([example](https://solscan.io/tx/2u9buyGjPRkrk7DMvEZwXpHA5W2TaUgqo6J3mc4vzGroLQMvZSraxSkW9QGT1Nkg9KBmhvRy9uxZzAgmGNcg7Yaj)). I think because of this NULL for `index` and `inner_index` makes sense. We can just default `swap_index` to 0.
> 
> ```
> select *
> from solana.silver.swaps
> where tx_id = '2u9buyGjPRkrk7DMvEZwXpHA5W2TaUgqo6J3mc4vzGroLQMvZSraxSkW9QGT1Nkg9KBmhvRy9uxZzAgmGNcg7Yaj'
> and program_id = 'JUP4Fb2cqiRUcaTHdrPC8h2gNsA2ETXiPDD33WcGuJB'
> and block_timestamp::date = '2023-02-13';
> ```
> 
> We should note this in the table description + column description that v4 data before XYZ date has these conditions.
> 
> ## v5
> There are no inner instruction swaps here so we can use `swap_index` = index, inner_index = NULL and `swap_index` = row_number() func
> 
> ```
> select tx_id, swap_index
> from solana.silver.swaps_intermediate_jupiterv5_1
> group by 1,2
> having count(*) > 1;
> 
> select tx_id, swap_index
> from solana.silver.swaps_intermediate_jupiterv5_2
> group by 1,2
> having count(*) > 1;
> ```

2024-11-13 16:14 UTC, desmond-hui requested changes

2024-11-13 16:14 UTC, desmond-hui commented on models/gold/defi/defi__fact_swaps_jupiter_summary.yml
> +    description: This table contains summarized swaps for trades initiated on Jupiter. This showcases the the initial amount/mint that is swapped from and the final amount/mint that is swapped to, wi
I would add that for these V4 swaps, they are aggregated at the transaction level and that is why they have NULL index and inner_index

2024-11-13 16:14 UTC, desmond-hui commented on models/gold/defi/defi__fact_swaps_jupiter_summary.sql
This view doesn't run with the latest changes. Looks like you will have to move the changes upstream. I would consider doing the window function on the static tables instead so that it doesnt have to redo the window function every single time this view is queried (or change this to a table).

Error when I try to run the view
```
16:11:28    Database Error in model defi__fact_swaps_jupiter_summary (models/gold/defi/defi__fact_swaps_jupiter_summary.sql)
  091949 (0A000): SQL compilation error: line 0 at position -1:
  Change tracking is not supported on queries with window functions that have disjoint partition keys.
  compiled Code at target/run/solana_models/models/gold/defi/defi__fact_swaps_jupiter_summary.sql
```

2024-11-14 00:03 UTC, tarikceric commented on models/gold/defi/defi__fact_swaps_jupiter_summary.sql
The best solution seems like just converting to tables:

fr on 2xl:
```
23:28:50  2 of 2 OK created sql incremental model defi.fact_swaps_jupiter_summary ........ [SUCCESS 1 in 165.88s]
23:29:38  1 of 2 OK created sql incremental model defi.fact_swaps_jupiter_inner .......... [SUCCESS 1 in 213.32s]
```

inc of medium:
```
23:55:01  2 of 2 OK created sql incremental model defi.fact_swaps_jupiter_summary ........ [SUCCESS 334129 in 15.59s]
23:55:04  1 of 2 OK created sql incremental model defi.fact_swaps_jupiter_inner .......... [SUCCESS 577075 in 18.19s]
```

tests:
```
23:56:57  Finished running 67 data tests, 7 project hooks in 0 hours 1 minutes and 21.49 seconds (81.49s).
```

2024-11-14 00:03 UTC, tarikceric commented on models/gold/defi/defi__fact_swaps_jupiter_summary.yml
> +    description: This table contains summarized swaps for trades initiated on Jupiter. This showcases the the initial amount/mint that is swapped from and the final amount/mint that is swapped to, wi
updated comment

2024-11-14 15:54 UTC, desmond-hui approved these changes

2024-11-29 18:47 UTC, merged