An 5383/nft sales updates
FlipsideCrypto/solana-models pull request #737
Opened 2024-12-13 00:11 UTC by tarikceric

create nft_sales_hadeswap_decoded and nft_sales_tensor_bid
- deprecate old hadeswap and update gold table

Decoded instructions return errors up to 2023-02-08 so use legacy model
- delete legacy records in gold via:
```
delete from SOLANA.nft.fact_nft_sales
where block_timestamp::date > '2023-02-08'
and program_id = 'hadeK9DLv9eA7ya5KCTqSvSvRZeJC3JgD5a9Y3CNbvu';
```

- gold table run on m
23:53:16  1 of 1 OK created sql incremental model nft.fact_nft_sales ..................... [SUCCESS 126343 in 14.00s]

- fr hadeswap and tensor_bid on 2xl
23:21:33  1 of 1 OK created sql incremental model silver.nft_sales_hadeswap_decoded ...... [SUCCESS 1 in 399.75s]
20:29:08  2 of 2 OK created sql incremental model silver.nft_sales_tensor_bid ............ [SUCCESS 1 in 10.30s]

2024-12-14 00:20 UTC, desmond-hui requested changes

2024-12-14 00:20 UTC, desmond-hui commented on models/silver/nfts/silver__nft_sales_hadeswap_decoded.sql
> +    succeeded,
any reason to not surface `index`, `inner_index` in this model?

2024-12-14 00:20 UTC, desmond-hui commented on models/silver/nfts/silver__nft_sales_tensor_bid.sql
> +    TRUE as succeeded,
any reason to not surface `index`, `inner_index` in this model?

2024-12-14 00:20 UTC, desmond-hui commented on models/silver/nfts/silver__nft_sales_tensor_bid.yml
> +    tests:
Lets add a relationships test with `decoded_instructions_combined`

2024-12-14 00:20 UTC, desmond-hui commented on models/silver/nfts/silver__nft_sales_hadeswap_decoded.yml
> +    tests:
Lets add a relationships test with `decoded_instructions_combined`

2024-12-14 00:20 UTC, desmond-hui commented on models/silver/nfts/silver__nft_sales_tensor_bid.yml
change `tests:` to `data_tests:`

2024-12-14 00:20 UTC, desmond-hui commented on models/silver/nfts/silver__nft_sales_hadeswap_decoded.yml
change `tests:` to `data_tests:`

2024-12-16 21:01 UTC, tarikceric commented on models/silver/nfts/silver__nft_sales_tensor_bid.yml
updated

2024-12-16 21:01 UTC, tarikceric commented on models/silver/nfts/silver__nft_sales_tensor_bid.yml
> +    tests:
added

2024-12-16 21:01 UTC, tarikceric commented on models/silver/nfts/silver__nft_sales_hadeswap_decoded.sql
> +    succeeded,
good point, added

2024-12-18 00:05 UTC, desmond-hui approved these changes

2024-12-18 00:51 UTC, merged