An 1937/blocks txs2
FlipsideCrypto/solana-models pull request #94
Opened 2022-09-06 18:39 UTC by jhuhnke

2022-09-06 22:12 UTC, desmond-hui requested changes

2022-09-06 22:12 UTC, desmond-hui commented on models/bronze/bronze__blocks2.sql
> +    solana.bronze.blocks_api
need to change to dbt ref

2022-09-06 22:12 UTC, desmond-hui commented on models/bronze/bronze__transactions2.sql
> +    solana.bronze.block_txs_api
need to change to dbt ref

2022-09-06 22:12 UTC, desmond-hui commented on models/sources.yml
> +      - name: block_txs_api
What are the purpose of these? They are part of `solana_external` or do you want to add them so that we always can reference to the `prod` data?

2022-09-07 18:34 UTC, jhuhnke commented on models/sources.yml
> +      - name: block_txs_api
Left over from early dev days. Deleting

2022-09-07 18:47 UTC, desmond-hui approved these changes

2022-09-07 18:52 UTC, merged